### ISSUE TITLE
Licensing query

### ISSUE THREAD

**Issue by ckormanyos** [Chalandi/OSEK_Raspberry_Pi_Zero#5]
Hi Amine (@Chalandi) I have found your licensing in this repo to be "none". This is fine, being none.

I wanted, however, to query:
- Do you intend to or will you be adding any licensing to the code in this repo?

**Comment by Chalandi** [comment]
Hi Chris (@ckormanyos ),

Yes, I could add one. What do you suggest ?

**Comment by ckormanyos** [comment]
> I could add one. What do you suggest ?

Hi Amine (@Chalandi)

It depends on your personal preference. For self-written, non-proprietary code (such as in this repo, I believe), I have been happy with the Boost-Software-License (BSL 1.0).

I can work up a PR for adding this license and a badge for it.

**Comment by ckormanyos** [comment]
Thanks Amine (@Chalandi).

Fixed by cd441ce9953827f5eb84395462dd5ac8cda1e330
